version: '3.8'
services:

  nest-backend-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Openzeka.1234
      - POSTGRES_DB=cordatus
    volumes:
      - backend-nest-db:/var/lib/postgresql/data
    ports:
      - '5001:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
    - /var/lib/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: yarn run start:dev api-gateway
    depends_on:
      rabbitmq:
        condition: service_started
      nest-backend-db:
        condition: service_healthy
    volumes:
    - "./:/app"
    - /app/node_modules
    ports:
    - '8030:3000'
    env_file:
      - "./.env"

  devices:
    build:
      context: .
      dockerfile: ./apps/devices/Dockerfile
    command: yarn run start:dev devices && npx prisma migrate dev --schema libs/prisma/schema/devices/schema.prisma
    depends_on:
      api-gateway:
        condition: service_started
      rabbitmq:
        condition: service_started
      nest-backend-db:
        condition: service_healthy
    
    ports:
    - '8031:3000'
    volumes:
    - .:/app
    - /app/node_modules

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    command: yarn run start:dev users && npx prisma migrate dev --schema libs/prisma/schema/users/schema.prisma
    depends_on:
      api-gateway:
        condition: service_started
      rabbitmq:
        condition: service_started
      nest-backend-db:
        condition: service_healthy
    ports:
    - '8032:3000'
    volumes:
    - .:/app
    - /app/node_modules

  jobs:
    build:
      context: .
      dockerfile: ./apps/jobs/Dockerfile
    command: yarn run start:dev jobs && npx prisma migrate dev --schema libs/prisma/schema/jobs/schema.prisma
    depends_on:
      api-gateway:
        condition: service_started
      rabbitmq:
        condition: service_started
      nest-backend-db:
        condition: service_healthy
    ports:
    - '8033:3000'
    volumes:
    - .:/app
    - /app/node_modules

volumes:
  backend-nest-db:
